version: '3'
services: 
        web: 
                build: 
                        context: .
                        dockerfile: Dockerfile.dev                             
                ports: 
                        - "3000:3000"
                volumes:
                        - /app/node_modules                        
                        - .:/app                                
        ##another container who's soul perpose
        ##is to create a test suite which 
        ##also uses live mount points (the only reason we are making this)
        test:
                build:
                        context: .
                        dockerfile: Dockerfile.dev 
                volumes:
                        - /app/node_modules
                        - .:/app                                 
                command:
                        ["npm","run","test"]

